config/routes.rb
Rails.application.routes.draw do

  resources :users do
     member do
       get :following, :followers
     end
  end

  resources :entries do
    resources :comments
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :relationships, only: [:create, :destroy]
  root  'entries#index'
  match '/signup', to: 'users#new', via: 'get'
  match '/signin',  to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

end

app/models/entry.rb
class Entry < ActiveRecord::Base

  validates :body, presence: true
  validates :title, presence: true
  has_many :comments, :dependent => :destroy
  default_scope -> { order('created_at DESC') }
  belongs_to :user

  def self.from_users_followed_by(user)
    followed_user_ids = "SELECT followed_id FROM relationships
                         WHERE follower_id = :user_id"
    where("user_id IN (#{followed_user_ids}) OR user_id = :user_id",
          user_id: user.id)
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: [:show, :edit, :update, :destroy]
  before_action :signed_in_user, except: [:show, :index]

  # GET /entries
  # GET /entries.json
  def index
    @feeds = signed_in? ? current_user.feed() : Entry.all
    @entries = @feeds.paginate(:page => params[:page], :per_page => 3).order('created_at DESC')
    # byebug
  end

  # GET /entries/1
  # GET /entries/1.json
  def show
    @entry = Entry.find(params[:id])
    @comments = @entry.comments.paginate(:page =>  params[:page], :per_page =>  3).order('created_at DESC')
    @comment = Comment.new
  end

  # GET /entries/new
  def new
    @entry = Entry.new
  end

  # GET /entries/1/edit
  def edit
  end

  # POST /entries
  # POST /entries.json
  def create
    @entry = current_user.entries.build(entry_params)
    if @entry.save
      redirect_to @entry, notice: 'Entry was successfully created.'
    else
      render :new
    end
    # Format code
    #
    # respond_to do |format|
    #   if @entry.save
    #     format.html { redirect_to @entry, notice: 'Entry was successfully created.' }
    #     format.json { render :show, status: :created, location: @entry }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @entry.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PATCH/PUT /entries/1
  # PATCH/PUT /entries/1.json
  def update
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to @entry, notice: 'Entry was successfully updated.' }
        format.json { render :show, status: :ok, location: @entry }
      else
        format.html { render :edit }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1
  # DELETE /entries/1.json
  def destroy
    @entry.destroy
    respond_to do |format|
      format.html { redirect_to entries_url, notice: 'Entry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def entry_params
      params.require(:entry).permit(:title, :body)
    end


end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/_entry.html.erb
  <h1 style="text-decoration: none"><%= link_to(entry.title, entry) %></h1>

  <h5><%= entry.body %></h5>
  <br />
  <span class="timestamp">
    Posted <%= time_ago_in_words(entry.created_at) %> ago.
  </span>
  <% if current_user?(entry.user) %>
    <%= link_to "delete", entry, method: :delete,
                                     data: { confirm: "You sure?" },
                                     title: entry.title %>
  <% end %>

app/views/entries/_form.html.erb
<%= form_for(@entry) do |f| %>
  <% if @entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
      <% @entry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/entries/edit.html.erb
<h1>Editing Entry</h1>

<%= render 'form' %>

<%= link_to 'Show', @entry %> |
<%= link_to 'Back', entries_path %>

app/views/entries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Entries</h1>

  <% @entries.each do |entry| %>

    <%= div_for entry do %>
    <p>
      <h3><%= link_to(entry.title, entry_path(entry.title)) %></h3>
      <h5><%= entry.body %> </h5>
      <strong>Posted <%= time_ago_in_words(entry.created_at) %> ago</strong> |
        <%= link_to 'Edit', edit_entry_path(entry) %> | <%= link_to 'Destroy', entry, method: :delete, data: { confirm: 'Are you sure?' } %>

    </p>
  <% end %>

      <!-- <tr>
        <td><%= entry.title %></td>
        <td><%= entry.body %></td>
        <td><%= link_to 'Show', entry %></td>
        <td><%= link_to 'Edit', edit_entry_path(entry) %></td>
        <td><%= link_to 'Destroy', entry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr> -->
    <% end %>

 <%= will_paginate @entries %>

<br>

<h3><%= link_to 'New Entry', new_entry_path %></h3>

app/views/entries/new.html.erb
<h1>New Entry</h1>

<%= render 'form' %>

<%= link_to 'Back', entries_path %>

app/views/entries/show.html.erb
<p id="notice"><%= notice %></p>


<%= render :partial => @entry %>

 <%= link_to 'Edit', edit_entry_path(@entry) %> |
 <%= link_to 'Back', entries_path %>

<%#= link_to 'Edit', edit_entry_path(@entry) %>
<%#= link_to 'Back', entries_path %>

<h2>Comments</h2>
<div id="comments">
  <%= render :partial => @comments %>
  <%= will_paginate @comments %>
</div>


<%= form_for([@entry, @comment])do |f| %>
<p>
  <%= f.label :body, "New comment" %>
  <%= f.text_area :body %>
</p>
<p><%= f.submit "Add comment" %> </p>
<% end %>