config/routes.rb
Rails.application.routes.draw do

  resources :users do
     member do
       get :following, :followers
     end
  end

  resources :entries do
    resources :comments
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :relationships, only: [:create, :destroy]
  root  'entries#index'
  match '/signup', to: 'users#new', via: 'get'
  match '/signin',  to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
 <!--  <small>
    <%= link_to "Rails Tutorial", 'http://railstutorial.org/' %> by Michael Hartl
    <a href="http://railstutorial.org/">Rails Tutorial</a>
    by Michael Hartl
  </small> -->
  <nav>
    <ul>
      <li><%= link_to "About", "#" %></li>
      <li><%= link_to "Contact", "#" %></li>
      <!-- <li><a href="http://news.railstutorial.org/">News</a></li> -->
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-container">
    <div class="container">
      <%= link_to "My Blog", '#', id:"logo", class: "navbar-brand" %>
      <nav>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Home", root_path %> </li>
          <li><%= link_to "Help", "#" %></li>
          <% if signed_in? %>
          <li><%= link_to "Users", users_path %></li>
          <li class="dropdown" id="dropdownMenuDivider"><a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="true">
              <%= current_user.name %> <b class="caret"></b>
            </a>

            <ul class="dropdown-menu" aria-labelledby="dropdownMenuDivider">
              <li> <%= link_to "Profile" , current_user %></li>
               <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <!-- <li class="disabled"><a href="#">Disabled link</a></li> -->
              <li class="divider"></li>
              <li> <%= link_to("Sign Out", signout_path , method: "delete") %></li>
            </ul>
            </li>

          <% else %>
          <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>

<%= render 'layouts/header' %>

<div class="container">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>
  <%= yield %>
  <%= render 'layouts/footer' %>
   <!-- <%= debug(params) if Rails.env.development? %> -->
</div>

</body>
</html>